modules/apps/controllers/SiteController.php
<?php

namespace app\modules\apps\controllers;

use app\helpers\Configtype;
use app\helpers\OrderUtils;
use app\helpers\Rolename;
use app\helpers\Utils;
use app\models\Addresses;
use app\models\Cities;
use app\models\Configweb;
use app\models\ContactForm;
use app\models\LoginForm;
use app\models\Provinces;
use app\models\User;
use app\models\Users;
use Yii;
use yii\db\Exception;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\Response;
use const YII_ENV_TEST;

class SiteController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
        if (User::me()->role == Rolename::SUPER_ADMIN) {
            return $this->redirect(['/admins/products']);
        } else {
            return $this->redirect(['p']);
        }
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            if (User::me()->role == Rolename::SUPER_ADMIN) {
                return $this->redirect(['index']);
            }
            return $this->goBack();
        }

        //$model->password = '';
        return $this->render('login', [
                    'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout() {
        Yii::$app->user->logout();
        OrderUtils::removeAllCart();
        return $this->goHome();
    }

    public function actionRegister() {
        $model = new Users(['scenario' => 'register']);
        $provinces = ArrayHelper::map(Provinces::find()->all(), 'province_id', 'province');
        $cities = ArrayHelper::map(Cities::find()->all(), 'city_id', 'city_name');

        $msg = null;
        $transaction = \Yii::$app->db->beginTransaction();
        if ($model->load(Yii::$app->request->post())) {
            try {
                $tmpPassword = $model->password;
                $model->iduser = Utils::getNextID('iduser', Users::tableName());
                $model->username = Utils::getCharBeforeFind($model->email, '@') . Utils::randDigit();
                $model->userkey = Utils::getID();
                $model->status = Utils::STAT_ACTIVE;
                $model->role = Rolename::CUSTOMER;
                $model->password = md5($model->password);

                if ($model->save()) {
                    $prov = Provinces::findOne($model->province_id);
                    $city = Cities::findOne($model->city_id);
                    $m_addr = new Addresses();
                    $m_addr->idaddress = Utils::getNextID('idaddress', Addresses::tableName());
                    $m_addr->iduser = $model->iduser;
                    $m_addr->province_id = $model->province_id;
                    $m_addr->city_id = $model->city_id;
                    $m_addr->province_name = ($prov ? $prov->province : null);
                    $m_addr->city_name = ($city ? $city->city_name : null);
                    $m_addr->address = $model->address;
                    $m_addr->postal_code = $model->postal_code;
                    $m_addr->status = Utils::STAT_ACTIVE;
                    $m_addr->phone = $model->phone;
                    if (!$m_addr->save()) {
                        $msg = json_encode($m_addr->getErrors());
                        Utils::flashDanger($msg);
                        $transaction->rollBack();
                    }
                } else {
                    $msg = json_encode($model->getErrors());
                    Utils::flashDanger($msg);
                    $transaction->rollBack();
                }
                $model->password = $tmpPassword;
                
                $transaction->commit();
                Utils::flashSuccess('Berhasil Registrasi, email <code>' . $model->email . '</code>, username <code>' . $model->username . '</code>');
                return $this->goBack();
            } catch (Exception $e) {
                $transaction->rollBack();
            }
        }

        return $this->render('register', [
                    'model' => $model,
                    'provinces' => $provinces,
                    'cities' => $cities,
        ]);
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact() {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
                    'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionFindus() {
        return $this->render('findus', [
                    //'data' => $data
        ]);
    }

    public function actionTest() {
        $curDay = date('Y-m-d H:i:s');
        \app\components\Sendmail::sendTest('qyaraofficial2020@gmail.com');
        echo '<pre>';
        print_r($curDay);
        die;
        $order = \app\models\Orders::find()
                ->where(['status' => OrderUtils::STAT_ONSHIPPING])
                ->orderBy(['orderdate' => SORT_DESC])
                ->all();

        foreach ($order as $perOrder) {
            $howDayShip = strtotime('+14 day', strtotime($perOrder->shipdate));
            $curDay = strtotime(date('Y-m-d'));
            if ($curDay >= $howDayShip) {
                $m_order = \app\models\Orders::findOne(['idorder' => $perOrder->idorder]);
                if ($m_order) {
                    $m_order->status = OrderUtils::STAT_DONE;
                }
            }
        }
    }

}

modules/apps/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

modules/apps/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-index error-page" style="padding-bottom: 170px"> 

    <h1 style="font-size: 30px;"><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger" style="margin-top:30px;">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>
    
</div>

modules/apps/views/site/findus.php
<?php
/* @var $this View */

use app\helpers\Configtype;
use app\helpers\Url;
use app\models\Configwebs;
use yii\web\View;

$this->title = 'Temukan Kami';
?>

<div class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__links">
                    <a href="<?= Url::base() . '/apps' ?>"><i class="fa fa-home"></i> Beranda</a>
                    <span><?= $this->title ?></span>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="blog-details spad" style="padding-top: 10px;">
    <div class="container">
        <div class="blog__details__content">
            <div class="links__item">
                <?php
                $findUs = Configwebs::find()
                        ->where(['type' => Configtype::FIND_US])
                        ->orderBy(['idconfig' => SORT_ASC])
                        ->all();
                
                foreach ($findUs as $perData) {
                    $color = $perData->note ? 'color:' . $perData->note . ';' : null;
                    $link = $perData->name ? $perData->name : '#';
                    echo '<a href="' . $link . '" target="_blank">
                    <div class="card mb-12 a-link" style="max-width: 540px;">
                        <div class="row no-gutters">
                            <div class="col-md-9">
                                <div class="card-body">
                                    <h5 style="font-weight:bold;' . $color . '">' . $perData->description . '</h5>
                                </div>
                            </div>
                            <div class="col-md-3 pull-right">
                            </div>
                        </div>
                    </div>
                    </a></br>';
                }
                ?>

            </div>
        </div>
    </div>
</section>

modules/apps/views/site/login.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

$this->title = 'Login';
$css = '.site-login{margin-top: 150px;
    margin-left: auto;
    margin-right: auto;
    width: 300px;
    margin-bottom: 100px;
    }';
$this->registerCss($css);
?>
<div class="site-login">
    <h3><?= Html::encode($this->title) ?></h3>
    <br>
    <?php
    $form = ActiveForm::begin([
                'id' => 'login-form',
    ]);
    ?>

    <?= $form->field($model, 'username')->textInput(['autofocus' => true])->label('Username / email') ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'rememberMe')->checkbox([]) ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11" style="padding: 0px;">
            <?= Html::submitButton('Login', [
                'class' => 'btn btn-primary', 
                'name' => 'login-button',
                'style' => 'width:300px;'
                ]) ?>
        </div>
    </div>
    <hr>
    <p class="text-center">Belum punya akun, Silahkan <?= Html::a('Daftar', ['site/register'])?></p>
    <?php ActiveForm::end(); ?>
</div>

modules/apps/views/site/register.php
<?php
/* @var $this View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use app\helpers\Url;
use kartik\depdrop\DepDrop;
use kartik\select2\Select2;
use yii\bootstrap4\ActiveForm;
use yii\helpers\Html;
use yii\web\View;

$this->title = 'Registrasi';
$css = '.site-login{margin-top: 150px;
    margin-left: auto;
    margin-right: auto;
    width: 300px;
    margin-bottom: 100px;
    }';
//$this->registerCss($css);
?>
<div class="site-login">

    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__links">
                        <a href="./index.html"><i class="fa fa-home"></i> Home</a>
                        <span>Daftar</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
<!--    <h3><?= Html::encode($this->title) ?></h3>-->
    <section class="checkout spad">
        <div class="container">
            <?php $form = ActiveForm::begin(['options' => ['class' => 'checkout__form']]); ?>
            <div class="row">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="checkout__form__input">
                                <?= $form->field($model, 'name') ?>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="checkout__form__input">
                                <?= $form->field($model, 'lastname') ?>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="checkout__form__input">
                                <?= $form->field($model, 'email') ?>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="checkout__form__input">
                                <?= $form->field($model, 'phone') ?>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="checkout__form__input">
                                <?= $form->field($model, 'password')->passwordInput() ?>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="checkout__form__input">
                                <?= $form->field($model, 'passconfirm')->passwordInput() ?>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="checkout__form__input">
                                <?php
                                echo $form->field($model, 'province_id')->widget(Select2::classname(), [
                                    'data' => $provinces,
                                    'options' => [
                                        'placeholder' => '-- Pilih Provinsi --',
                                        'id' => 'province_id',
                                    ],
                                    'pluginOptions' => [
                                        'allowClear' => true
                                    ],
                                ])->label('Provinsi');
                                ?>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="checkout__form__input">
                                <?=
                                $form->field($model, 'city_id')->widget(DepDrop::classname(), [
                                    'data' => $cities,
                                    'type' => DepDrop::TYPE_SELECT2,
                                    'options' =>
                                    [
                                        'id' => 'city_id',
                                        'placeholder' => Yii::t('app', '--Pilih Kabupaten / Kota--'),
                                    ],
                                    'select2Options' => ['pluginOptions' => ['allowClear' => true]],
                                    'pluginOptions' => [
                                        'depends' => ['province_id'],
                                        'url' => Url::to(['/apps/api/depcity']),
                                        'placeholder' => Yii::t('app', '--Pilih Semua--'),
                                        'allowClear' => true,
                                    ]
                                ])->label('Kabupaten / Kota');
                                ?>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="checkout__form__input">
                                <?= $form->field($model, 'district') ?>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="checkout__form__input">
                                <?= $form->field($model, 'postal_code')->label('Kode Pos') ?>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="checkout__form__input">
                                <?= $form->field($model, 'address')->textarea(['rows' => '6'])->label('Alamat') ?>
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <div class="checkout__form__checkbox">
                                <label for="acc">
                                    Create an acount?
                                    <input type="checkbox" id="acc">
                                    <span class="checkmark"></span>
                                </label>
                                <p>Create am acount by entering the information below. If you are a returing
                                    customer login at the <br />top of the page</p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="form-group">
                <?=
                Html::submitButton('Daftar', [
                    'class' => 'btn btn-primary',
                    'data' => [
                        'confirm' => 'Apakah anda yakin data anda sudah benar ?',
                    ],
                ])
                ?>
            </div>
            <?php ActiveForm::end(); ?>

        </div>
    </section>
</div>