modules/apps/controllers/CheckoutController.php
<?php

namespace app\modules\apps\controllers;

use app\components\AdminController;
use app\components\Sendmail;
use app\helpers\Configtype;
use app\helpers\DateUtils;
use app\helpers\OrderUtils;
use app\helpers\Utils;
use app\models\Addresses;
use app\models\Checkout;
use app\models\Couriers;
use app\models\Orderdetails;
use app\models\Orders;
use app\models\Payments;
use app\models\Shippers;
use app\models\User;
use Yii;
use yii\web\NotFoundHttpException;

/**
 * Default controller for the `apps` module
 */
class CheckoutController extends AdminController {

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex() {
        $model = new Checkout();
        $storeInfo = Configtype::getStoreInfo();
        $user = User::me();
        $addressActive = Addresses::findOne(['iduser' => $user->iduser, 'status' => Utils::STAT_ACTIVE]);

        $model->name = $user->name;
        $model->lastname = $user->lastname;
        $model->email = $user->email;
        $model->phone = ($addressActive ? $addressActive->phone : $user->phone);
        $model->province_id = ($addressActive ? $addressActive->province_id : null);
        $model->city_id = ($addressActive ? $addressActive->city_id : null);
        $model->province = ($addressActive ? $addressActive->province_name : null);
        $model->city = ($addressActive ? $addressActive->city_name : null);
        $model->district = ($addressActive ? $addressActive->district : null);
        $model->address = ($addressActive ? $addressActive->address : null);
        $model->postal_code = ($addressActive ? $addressActive->postal_code : null);

        $dataCart = OrderUtils::checkQtyCart();
        if (!$dataCart) {
            Utils::flashWarning('Keranjang Belanja Kosong.');
            return $this->redirect(['/apps/']);
        }
        $dataTotal = OrderUtils::getTotalPriceCartNew($dataCart, false);
        $total = $dataTotal['total'];
        $totalDiscount = $dataTotal['totalDiscount'];
        $totalQty = $dataTotal['totalQty'];
        $totalWeight = OrderUtils::getTotalWeightCart($dataCart);
        $msg = null;

        if (Yii::$app->request->isPost) {

            $transaction = \Yii::$app->db->beginTransaction();
            $m_order = new Orders();
            try {
                $m_order->idorder = Utils::getID();
                $m_order->orderdate = DateUtils::datetimeNow();
                $m_order->status = 1;
                $m_order->idcustomer = $user->iduser;
                $m_order->invoicekey = 'INV' . $m_order->idorder;
                $m_order->note = $_POST['Checkout']['note'];
                $m_order->totalweight = $totalWeight;
                $m_order->totalprice = $total;
                $idcourier = $_POST['Checkout']['idcourier'];
                $m_order->idpayment = $_POST['idpayment'];
                $m_order->paymentname = $_POST['bankname'];
                $m_order->typepayment = '123124356';
                $m_typepayment = Payments::findOne($m_order->typepayment);
                $m_order->typepaymentname = $m_typepayment ? $m_typepayment->name : '-';

                if ($m_order->save()) {
                    OrderUtils::saveOrderLog($m_order);
                    $m_shipment = new Shippers();
                    $m_shipment->idshipping = Utils::getID();
                    $m_shipment->idorder = $m_order->idorder;
                    $m_shipment->idprovorigin = $model->province_id;
                    $m_shipment->nameprovorigin = $storeInfo->province_name;
                    $m_shipment->idcityorigin = $storeInfo->city_id;
                    $m_shipment->namecityorigin = $storeInfo->city_name;
                    $m_shipment->idprovdestination = $model->province_id;
                    $m_shipment->nameprovdestination = $model->province;
                    $m_shipment->idcitydestination = $model->city_id;
                    $m_shipment->namecitydestination = $model->city;
                    $m_shipment->idcourier = $idcourier;
                    $m_courier = Couriers::findOne($idcourier);
                    $m_shipment->namecourier = ($m_courier ? $m_courier->name : '-');
                    $m_shipment->nameservice = $_POST['servicename'];
                    $m_shipment->cost = $_POST['ongkir'];
                    $m_shipment->weight = $totalWeight;
                    $m_shipment->address = $model->address;
                    $m_shipment->postal_code = $model->postal_code;
                    $m_shipment->address_phone = $model->phone;

                    if (!$m_shipment->save()) {
                        $msg = json_encode($m_shipment->getErrors());
                    }

                    $collectDet = [];
                    foreach ($dataCart as $key => $perItem) {
                        $m_orderdet = new Orderdetails();
                        $m_orderdet->idorderdetail = Utils::getID();
                        $m_orderdet->idorder = $m_order->idorder;
                        $m_orderdet->idproduct = $perItem['idproduct'];
                        $m_orderdet->idvarian = $perItem['idvarian'];
                        $m_orderdet->namevarian = $collectDet[$key]['namevarian'] = $perItem['name'];
                        $m_orderdet->price = $perItem['price'];
                        $m_orderdet->size = $perItem['size'];
                        $m_orderdet->weight = $perItem['weight'];
                        $m_orderdet->qty = $collectDet[$key]['qty'] = $perItem['qty'];
                        $m_orderdet->finalprice = OrderUtils::measurePrice($perItem['price'], $perItem['qty']);
                        $m_orderdet->finalweight = OrderUtils::measureWeight($perItem['weight'], $perItem['qty']);
                        $m_orderdet->img = $perItem['img'];
                        $m_orderdet->dateimg = $perItem['date'];
                        $m_orderdet->percent = ($perItem['percent'] == 0 ? null : $perItem['percent']);
                        $m_orderdet->oriprice = $perItem['oriPrice'];
                        if (!$m_orderdet->save()) {
                            $msg = json_encode($m_orderdet->getErrors());
                        } else {
                            OrderUtils::cutQty($m_orderdet->idvarian, $m_orderdet->qty);
                        }
                    }

                    $namevarian = OrderUtils::textVarian($collectDet);
                    $tQty = OrderUtils::textVarian($collectDet, true);

                    $m_order_up = Orders::findOne($m_order->idorder);
                    Utils::isExist($m_order_up);

                    $m_order_up->namevarian = $collectDet ? $namevarian : null;
                    $m_order_up->totalqty = $collectDet ? $tQty : null;
                    $m_order_up->orderprice = $m_order_up->totalprice + $m_shipment->cost;
                    $m_order_up->save();

                    if ($msg) {
                        $transaction->rollBack();
                        Utils::flashDanger($msg);
                    } else {
                        $transaction->commit();
                        if ($user->email) {
                            Sendmail::sendMailPayment($user->email, $m_order->idorder);
                        }
                        OrderUtils::removeAllCart();
                        return $this->redirect(['paymentdet', 'ui' => $m_order->idorder]);
                    }
                } else {
                    $msg = json_encode($m_order->getErrors());
                    $transaction->rollBack();
                }
            } catch (Exception $ex) {
                $transaction->rollBack();
                Utils::flashDanger('Terjadi Kesalahan');
            }
        }

        return $this->render('index', [
                    'model' => $model,
                    'dataCart' => $dataCart,
                    'total' => $total,
                    'totalQty' => $totalQty,
                    'storeInfo' => $storeInfo,
                    'totalWeight' => $totalWeight,
        ]);
    }

    public function actionDelete() {
        if (Utils::req()->isPost) {
            OrderUtils::removeAllCart();
            return $this->redirect(['/apps/p']);
        }
        throw new NotFoundHttpException('Method Not Allowed.');
    }

    public function actionPaymentdet($ui) {
        $model = Orders::findOne($ui);
        Utils::isExist($model);
        $m_payment = Payments::findOne($model->idpayment);
        Utils::isExist($m_payment);
        $m_shipper = Shippers::findOne(['idorder' => $model->idorder]);
        Utils::isExist($m_shipper);

        return $this->render('paymentdet', [
                    'model' => $model,
                    'm_payment' => $m_payment,
                    'm_shipper' => $m_shipper,
        ]);
    }

}

modules/apps/controllers/CustomerController.php
<?php

namespace app\modules\apps\controllers;

use app\components\AdminController;
use app\components\Sendmail;
use app\helpers\Dlist;
use app\helpers\OrderUtils;
use app\helpers\Url;
use app\helpers\Utils;
use app\models\Addresses;
use app\models\Orderlog;
use app\models\Orders;
use app\models\User;
use app\models\Users;
use app\models\Verifypayment;
use Yii;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

/**
 * Default controller for the `apps` module
 */
class CustomerController extends AdminController {

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex() {
        $model = $this->findModel(User::me()->iduser);

        $waiting_payment = OrderUtils::getOrderData(User::me()->getId(), [OrderUtils::STAT_WAITING_PAYMENT, OrderUtils::STAT_PAYMENT_VERIFIED, OrderUtils::STAT_PAYMENT_VERIFICATION]);
        $onprocess = OrderUtils::getOrderData(User::me()->getId(), [OrderUtils::STAT_ONPROCESS]);
        $onshipping = OrderUtils::getOrderData(User::me()->getId(), [OrderUtils::STAT_ONSHIPPING]);
        $done = OrderUtils::getOrderData(User::me()->getId(), [OrderUtils::STAT_DONE]);
        $canceled = OrderUtils::getOrderData(User::me()->getId(), [OrderUtils::STAT_CANCELED]);

        return $this->render('index', [
                    'model' => $model,
                    'waiting_payment' => $waiting_payment,
                    'onprocess' => $onprocess,
                    'onshipping' => $onshipping,
                    'done' => $done,
                    'canceled' => $canceled
        ]);
    }

    public function actionVerifypayment() {
        $model = new Verifypayment();

        if ($model->load(Yii::$app->request->post())) {
            $transaction = \Yii::$app->db->beginTransaction();
            $msg = null;

            try {
                $img = UploadedFile::getInstance($model, 'img');
                if (strlen(trim($img)) > 0 && is_object($img)) {
                    $name = 'VP' . Utils::getID() . '.' . $img->extension;
                    $dataTime = date('Y-m-d H:i:s');
                    $path = Url::setupBaseImg($dataTime);
                    if ($img->saveAs($path . $name)) {
                        $model->date = $dataTime;
                        $model->img = $name;
                        if ($model->save()) {
                            $m_order = Orders::findOne($model->idorder);
                            if ($m_order) {
                                $m_order->status = OrderUtils::STAT_PAYMENT_VERIFICATION;
                                if (!$m_order->save()) {
                                    $msg = json_encode($m_order->getErrors());
                                } else {
                                    OrderUtils::saveOrderLog($m_order);
                                }
                            }

                            if (!$msg) {
                                $email = User::getStoreEmail();
                                if ($email) {
                                    Sendmail::sendMailConfirmPayment($email, $model->idorder);
                                }
                                $transaction->commit();
                                Utils::flashSuccess('Bukti Bembayaran berhasil dikirim.');
                                return $this->redirect(['index']);
                            }
                        }
                    }

                    $msg = json_encode($model->getErrors());
                    if ($msg) {
                        Utils::flashDanger('Gagal kirim bukti pembayaran. Silahkan Ulangi.' . $msg);
                        $pathImg = Url::getBaseImg($name, $dataTime, true);
                        if (is_file($pathImg)) {
                            unlink($pathImg);
                        }
                        $transaction->rollBack();
                    }
                }
            } catch (Exception $e) {
                Utils::flashDanger('Gagal disimpan');
                $transaction->rollBack();
            }
        }

        return $this->render('verifypayment', [
                    'model' => $model,
        ]);
    }

    public function actionAddress() {
        $model = Addresses::find()
                ->where(['iduser' => User::me()->getId()])
                ->one();

        return $this->render('address', [
                    'model' => $model,
                    'm_user' => User::me(),
        ]);
    }

    public function actionUpaddress($id) {
        $model = Addresses::findOne($id);
        $provinces = Dlist::dListProvince();
        $cities = Dlist::dListCity($model->province_id);
        $model->fullname = User::me()->name . ' ' . User::me()->lastname;

        if ($model->load(Yii::$app->request->post())) {
            $model->phone = trim($model->phone);
            $model->province_name = (isset($provinces[$model->province_id]) ? $provinces[$model->province_id] : null);
            $cities = Dlist::dListCity($model->province_id);
            $model->city_name = (isset($cities[$model->city_id]) ? $cities[$model->city_id] : null);

            if ($model->save()) {
                Utils::flashSuccess('Berhasil Update Alamat.');
                return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);
            }
        }

        return $this->renderAjax('_upaddress', [
                    'model' => $model,
                    'provinces' => $provinces,
                    'cities' => $cities,
        ]);
    }

    public function actionProfile() {
        $model = $this->findModel(User::me()->getId());

        if ($model->load(Yii::$app->request->post())) {
            if ($model->password != $model->oldAttributes['password']) {
                $model->password = md5($model->password);
            }

            if ($model->save()) {
                Utils::flashSuccess('Profile berhasil disimpan');
            } else {
                $msg = json_encode($model->getErrors());
                Utils::flashDanger($msg);
            }
        }

        return $this->render('profile', [
                    'model' => $model,
        ]);
    }

    public function actionAjaxdetailorder($id) {
        $dataOrder = OrderUtils::getOrderData(User::me()->getId(), null, $id);
        $orderLog = Orderlog::find()->where(['idorder' => $id])->asArray()->all();

        return $this->renderAjax('_detailOrder', [
                    'dataOrder' => $dataOrder,
                    'orderLog' => $orderLog,
        ]);
    }

    public function actionDetailorder($id) {
        $dataOrder = OrderUtils::getOrderData(User::me()->getId(), null, $id);
        $orderLog = Orderlog::find()->where(['idorder' => $id])->asArray()->all();

        return $this->render('detailorder', [
                    'dataOrder' => $dataOrder,
                    'orderLog' => $orderLog,
        ]);
    }

    protected function findModel($id) {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

modules/apps/views/checkout/_detailOrder.php
<?php
/* @var $this View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model LoginForm */

use app\helpers\OrderUtils;
use app\helpers\ProductHelper;
use app\helpers\Url;
use app\helpers\Utils;
use app\models\LoginForm;
use app\models\Orderdetails;
use app\models\Shippers;
use yii\web\View;
?>

<table width="100%">
    <tbody>
        <?php
        $dataOrder = Orderdetails::find()
                ->where(['idorder' => $model->idorder])
                ->asArray()
                ->all();

        $m_shipper = Shippers::findOne(['idorder' => $model->idorder]);
        Utils::isExist($m_shipper);

        $tWeight = [];
        $tPrice = [];
        if ($dataOrder) {
            foreach ($dataOrder as $perData) {
                $weightKg = OrderUtils::satuanKg($perData['finalweight']);
                $weight = $perData['finalweight'];
                echo '<tr style=" border-bottom: 1px solid rgba(0,0,0,.1);">
                        <td width="10%">
                            <img class="card-img" src="' . Url::getBaseImg($perData['img'], $perData['dateimg']) . '" alt="Card image cap" style="width: 75px;">
                        </td>
                        <td width="60%">
                            <small class="text-muted">&nbsp;&nbsp;' . (strlen($perData['namevarian']) > 40 ? substr($perData['namevarian'], 0, 40) . ' .....' : $perData['namevarian']) . '</small>
                            <p><small>&nbsp;&nbsp;' . $perData['qty'] . 'x (' . $weightKg . ') 
                                      &nbsp;<strong>' . ProductHelper::idrPrice($perData['price']) . '</strong>
                                </small>
                            </p>
                        </td>
                        <td width="30%" class="text-lg-right">
                            <span class="text-lg-right" style="padding-right: 20px;">' . ProductHelper::idrPrice($perData['finalprice']) . '</span>
                        </td>
                    </tr>';
                $tWeight[] = $weight;
                $tPrice[] = $perData['finalprice'];
            }
            $totalWeight = array_sum($tWeight);
            $totalPrice = array_sum($tPrice);
        }
        ?>
    </tbody>
</table>
<hr>
<div class="row">
    <div class="col-md-6"><p>Jasa Pengiriman : JNE REG (<?= OrderUtils::satuanKg($totalWeight) ?>)</p></div>
    <div class="col-md-6 text-lg-right"><span style="padding-right: 20px;"><?= ProductHelper::idrPrice($m_shipper->cost) ?></span></div>
</div>
<hr>
<hr>
<div class="row">
    <div class="col-md-6"><p><b>Total Tagihan</b></p></div>
    <div class="col-md-6 text-lg-right"><span style="padding-right: 20px;"><b><?= ProductHelper::idrPrice(OrderUtils::summaryPriceTotal($model->totalprice, $m_shipper->cost)) ?></b></span></div>
</div>

modules/apps/views/checkout/paymentdet.php
<?php
/* @var $this View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model LoginForm */

use app\helpers\OrderUtils;
use app\helpers\ProductHelper;
use app\helpers\Url;
use app\models\LoginForm;
use yii\helpers\Html;
use yii\web\View;

$this->title = 'Pembayaran';
?>
<div class="site-login">

    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__links">
                        <a href="./index.html"><i class="fa fa-home"></i> Home</a>
                        <span>Pembayaran</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <section class="checkout spad" style="padding-top: 40px;">
        <div class="container">
            <h6>Transfer Bank</h6>
            <div class="bd-callout bd-callout-warning">
                <h5 id="conveying-meaning-to-assistive-technologies"><?= $m_payment->name ?></h5>
                <hr>
                <p>
                    <img class="card-img float-right" src="<?= Url::getImg($m_payment->img, '/img/payment/') ?>" alt="image cap" style="max-width: 80px;">
                <p><small>No. Rekening</small></p>
                <h4 id="conveying-meaning-to-assistive-technologies">
                    <?= $m_payment->accountnumber ?>
                </h4>
                </p>
                <hr>
                <h5><?= $m_payment->accountname ?></h5>
            </div>
            <br>
            <h6>Detail Order</h6>
            <a href="#" data-toggle="collapse" data-target="#detailpayment">
                <div class="bd-callout bd-callout-qyara">
                    <h5 id="conveying-meaning-to-assistive-technologies">Total Tagihan <span class="caret"></span> <span class="float-right"><?= ProductHelper::idrPrice(OrderUtils::summaryPriceTotal($model->totalprice, $m_shipper->cost)) ?></span></h5>
                </div>
            </a>
            <div id="detailpayment" class="collapse" style="background-color: #f9f9f9;padding: 20px;">
                <?php
                echo $this->render('_detailOrder', [
                    'model' => $model,
                ]);
                ?>
            </div><br>

            <div class="alert alert-info" role="alert" style="margin-top: 5px;">
                <p>Silahkan transfer tagihan ke Nomor rekening di atas.</p>
                <hr>
                <p class="mb-0">Upload bukti transfer, ke menu <b><?= Html::a('Bukti Pembayaran', ['customer/verifypayment']) ?></b> untuk memverifikasi pembayaran anda.</p>
            </div>
        </div>
    </section>

</div>